//constants
export const LOAD_SENSOR_LIST = 'LOAD_SENSOR_LIST';
export const LOAD_SENSOR_INFO_YEAR = 'LOAD_SENSOR_INFO_YEAR';
export const LOAD_SENSOR_INFO_MONTH = 'LOAD_SENSOR_INFO_MONTH';
export const LOAD_UNIQUE_DATES = 'LOAD_UNIQUE_DATES';

//fetching
export const FETCHING_LIST = 'FETCHING_LIST';
export const FETCHING_INFO_YEAR = 'FETCHING_INFO_YEAR';
export const FETCHING_INFO_MONTH = 'FETCHING_INFO_MONTH';
export const FETCHING_UNIQUE_DATES = 'FETCHING_UNIQUE_DATES';

//indexes
export const SET_SELECTED_YEAR_INDEX = 'SET_SELECTED_YEAR_INDEX';
export const SET_SELECTED_MONTH_INDEX = 'SET_SELECTED_MONTH_INDEX';